job "tfc-agent" {
  datacenters = ["lab"]
  type        = "service"
  priority    = 10

  constraint {
    attribute = "${meta.network_node}"
    value     = "true"
  }

  update {
    max_parallel      = 1
    health_check      = "checks"
    min_healthy_time  = "5s"
    healthy_deadline  = "2m"
    progress_deadline = "3m"
    auto_revert       = true
    canary            = 0
  }

  group "tfc-agent" {
    count = 1

    restart {
      interval  = "2h"
      attempts  = 10
      delay     = "60s"
      mode      = "delay"
    }

    task "tfc-agent" {
      driver = "containerd-driver"

      env {
        TFC_AGENT_TOKEN = "kVqibqy9XBdUWQ.atlasv1.lwT7X3lrv5MO7hIYzk2vSvlLXRyj5XnLJjeWE8j6Obt0a6RFJ8xmRW0IsivnstMmrBo"
        TFC_AGENT_NAME  = "cerberus"
      }

      config {
        image         = "docker.io/hashicorp/tfc-agent:${RELEASE}"
        host_network  = true
      }

      template {
        data          = <<EOH
IMAGE_DIGEST={{ keyOrDefault "tfc-agent/config/image_digest" "1" }}
RELEASE={{ keyOrDefault "tfc-agent/config/release" "latest" }}
EOH
        destination   = "env_info"
        env           = true
      }

      resources {
        cpu    = 100
        memory = 128
      }
      kill_timeout  = "30s"
    }
  }
}
