job "tfc-agent" {
  datacenters = ["lab"]
  type        = "service"
  priority    = 10

  constraint {
    attribute = "${meta.network_node}"
    value     = "true"
  }

  update {
    max_parallel      = 1
    health_check      = "checks"
    min_healthy_time  = "5s"
    healthy_deadline  = "2m"
    progress_deadline = "3m"
    auto_revert       = true
    canary            = 0
  }

  group "tfc-agent" {
    count = 1

    restart {
      interval  = "2h"
      attempts  = 10
      delay     = "60s"
      mode      = "delay"
    }

    task "tfc-agent" {
      driver = "podman"

      env {
        TFC_AGENT_TOKEN = "{{YOUR_TFC_TOKEN_HERE}}"
        TFC_AGENT_NAME  = "tfc-agent"
      }

      config {
        image         = "docker://docker.io/hashicorp/tfc-agent:${RELEASE}"
        network_mode  = "host"
      }

      template {
        data          = "IMAGE_ID={{ keyOrDefault \"tfc-agent/config/image_id\" \"1\" }}\nRELEASE={{ keyOrDefault \"tfc-agent/config/release\" \"latest\"}}"
        destination   = "env_info"
        env           = true
      }

      resources {
        cpu    = 100
        memory = 128
      }

      kill_timeout = "30s"
    }
  }
}
